version: '3.7'
services:
  app:
    container_name: yt
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8011"
    volumes:
      - ./media:/app/media
    env_file:
      - .env