version: '3'
services:
  app:
    container_name: yt
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8011:5000"
    volumes:
      - ./media:/app/media
      - ./db:/app/db
    env_file:
      - .env
    restart: always
    deploy:
      resources:
        limits:
          memory: 400M
          cpus: '0.8'

networks:
  default:
    name: caddy_caddy
    driver: bridge
    external: true