version: '3.7'
services:
  app:
    container_name: yt
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8011"
    volumes:
      - ./media:/app/media
      - data.db:/app/data.db
    env_file:
      - .env

networks:
  default:
    name: caddy_caddy
    driver: bridge
    external: true